// <auto-generated />
using System;
using GameLog_Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameLog_Backend.Migrations
{
    [DbContext(typeof(GameLogContext))]
    [Migration("20260913234431_AddAuditLogs")]
    partial class AddAuditLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameLog_Backend.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AuditLogId");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoAcao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ValoresAntigos")
                        .HasColumnType("text");

                    b.Property<string>("ValoresNovos")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("GameLog_Backend.Entities.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AvaliacaoId");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Nota")
                        .HasColumnType("integer");

                    b.Property<string>("TextoAvaliacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataPublicacao");

                    b.HasIndex("EstaAtivo");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId", "JogoId")
                        .IsUnique()
                        .HasFilter("\"EstaAtivo\" = true");

                    b.ToTable("Avaliacoes", t =>
                        {
                            t.HasCheckConstraint("CK_Avaliacao_Nota_Range", "\"Nota\" >= 0 AND \"Nota\" <= 5");
                        });
                });

            modelBuilder.Entity("GameLog_Backend.Entities.BibliotecaJogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("BibliotecaJogoId");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataAtualizacao");

                    b.HasIndex("EstaAtivo");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId", "JogoId")
                        .IsUnique();

                    b.ToTable("ItensBiblioteca", (string)null);
                });

            modelBuilder.Entity("GameLog_Backend.Entities.CurtidaDeAvaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CurtidaDeAvaliacaoId");

                    b.Property<Guid?>("AvaliacaoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Curtida")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CurtidasDeAvaliacoes");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.CurtidaDeResposta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CurtidaDeRespostaId");

                    b.Property<bool>("Curtida")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RespostaDeAvaliacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RespostaDeAvaliacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CurtidasDeRespostas");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("EmpresaId");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("NomeEmpresa")
                        .IsUnique();

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("GeneroId");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("TituloGenero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TituloGenero")
                        .IsUnique();

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.ItemDeLista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ItemDeListaId");

                    b.Property<DateTime>("DataAdicionado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListaDeJogosId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("ListaDeJogosId", "JogoId")
                        .IsUnique();

                    b.ToTable("ItensDeListas", (string)null);
                });

            modelBuilder.Entity("GameLog_Backend.Entities.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("JogoId");

                    b.Property<int>("ClassificacaoIndicativa")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DataLancamento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<Guid?>("PublicadoraId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("DataLancamento");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EstaAtivo");

                    b.HasIndex("PublicadoraId");

                    b.HasIndex("Titulo")
                        .HasDatabaseName("idx_jogos_titulo_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Titulo"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Titulo"), new[] { "gin_trgm_ops" });

                    b.HasIndex("EstaAtivo", "DataLancamento");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.JogoFavoritoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("JogoFavoritoUsuarioId");

                    b.Property<bool>("EstaAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId", "Posicao")
                        .IsUnique();

                    b.ToTable("JogosFavoritosUsuarios", (string)null);
                });

            modelBuilder.Entity("GameLog_Backend.Entities.ListaDeJogos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ListaDeJogosId");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstaAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("EstaPublica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ListasDeJogos", (string)null);
                });

            modelBuilder.Entity("GameLog_Backend.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RefreshTokenId");

                    b.Property<string>("CriadoPorIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevogadoPorIp")
                        .HasColumnType("text");

                    b.Property<string>("SubstituidoPorToken")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("GameLog_Backend.Entities.RespostaDeAvaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RespostaDeAvaliacaoId");

                    b.Property<Guid?>("AvaliacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RespostasDeAvaliacao");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.SegueUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UsuarioSeguidoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioSeguidorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioSeguidoId");

                    b.HasIndex("UsuarioSeguidorId");

                    b.ToTable("SegueUsuarios");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("Bio")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("FotoDePerfil")
                        .HasColumnType("text");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GeneroJogo", b =>
                {
                    b.Property<Guid>("GenerosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JogosId")
                        .HasColumnType("uuid");

                    b.HasKey("GenerosId", "JogosId");

                    b.HasIndex("JogosId");

                    b.ToTable("JogoGenero", (string)null);
                });

            modelBuilder.Entity("GameLog_Backend.Entities.Avaliacao", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLog_Backend.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.BibliotecaJogo", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLog_Backend.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.CurtidaDeAvaliacao", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.Avaliacao", "Avaliacao")
                        .WithMany("CurtidasDeAvaliacao")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameLog_Backend.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Avaliacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.CurtidaDeResposta", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.RespostaDeAvaliacao", "RespostaDeAvaliacao")
                        .WithMany("CurtidasDeRespostas")
                        .HasForeignKey("RespostaDeAvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameLog_Backend.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RespostaDeAvaliacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.ItemDeLista", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLog_Backend.Entities.ListaDeJogos", "ListaDeJogos")
                        .WithMany("Itens")
                        .HasForeignKey("ListaDeJogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("ListaDeJogos");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.Jogo", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameLog_Backend.Entities.Empresa", "Publicadora")
                        .WithMany()
                        .HasForeignKey("PublicadoraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");

                    b.Navigation("Publicadora");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.JogoFavoritoUsuario", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLog_Backend.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.ListaDeJogos", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.RefreshToken", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.RespostaDeAvaliacao", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.Avaliacao", "Avaliacao")
                        .WithMany("RespostasDeAvaliacao")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameLog_Backend.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Avaliacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.SegueUsuario", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.Usuario", "UsuarioSeguido")
                        .WithMany()
                        .HasForeignKey("UsuarioSeguidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameLog_Backend.Entities.Usuario", "UsuarioSeguidor")
                        .WithMany()
                        .HasForeignKey("UsuarioSeguidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioSeguido");

                    b.Navigation("UsuarioSeguidor");
                });

            modelBuilder.Entity("GeneroJogo", b =>
                {
                    b.HasOne("GameLog_Backend.Entities.Genero", null)
                        .WithMany()
                        .HasForeignKey("GenerosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLog_Backend.Entities.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameLog_Backend.Entities.Avaliacao", b =>
                {
                    b.Navigation("CurtidasDeAvaliacao");

                    b.Navigation("RespostasDeAvaliacao");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.ListaDeJogos", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GameLog_Backend.Entities.RespostaDeAvaliacao", b =>
                {
                    b.Navigation("CurtidasDeRespostas");
                });
#pragma warning restore 612, 618
        }
    }
}
